#!/usr/bin/bash
# Purpose: Perform genotyping on simted reads using CAPG
# INPUT: SAM files generated by simulation.sh
# OUTPUT: err files generated by CAPG, individual VCF files

REFA=/path/refA.fa
REFB=/path/refB.fa
SAMA=/path/SAMA
SAMB=/path/SAMB
EXTRACTED=/path/extracted
VCFA=/path/vcf_A_new
VCFB=/path/vcf_B_new
ERR_FILE=/path/err_files_new
INFO_A=/path/info_A
INFO_B=/path/info_B
EXE=roshan
NCPU=5

function wait_on {
        NUM=`pgrep -c $EXE`
        while [ $NUM -ge $NCPU ]
        do
                echo "$NUM $EXE running..."
                sleep 2
                NUM=`pgrep -c $EXE`
        done
}

for GENOTYPE in aln0 aln1 aln2 aln3 aln4 aln5 aln6 aln7 aln8 aln9 aln10 aln11 aln12 aln13 aln14 aln15 aln16 aln17 aln18 aln19 aln20 aln21 aln22 aln23 aln24 aln25 aln26 aln27 aln28 aln29 aln30 aln31 aln32 aln33 aln34 aln35 aln36 aln37 aln38 aln39 aln40 aln41 aln42 aln43 aln44 aln45 aln46 aln47 aln48 aln49;
do
	CMD="../script_main/roshan --geno /home/peanut/peanut2/CAPG/WGS/simulation/homr0.005/ref.sam --fsa_files $REFA $REFB --sam_files $SAMA/${GENOTYPE}A.sam $SAMB/${GENOTYPE}B.sam --ref_names Genome_A:0-100000 Genome_B:0-100000 -j $EXTRACTED/${GENOTYPE}_extracted.fsa --vcf_files $VCFA/${GENOTYPE}-A.vcf $VCFB/${GENOTYPE}-B.vcf --name ${GENOTYPE} -o $INFO_A/${GENOTYPE}-A_info.txt $INFO_B/${GENOTYPE}-B_info.txt -po"
	wait_on
	$CMD 2> $ERR_FILE/${GENOTYPE}.err &
done
